version: "1"
services:
  flink:
    image: registry.cn-hangzhou.aliyuncs.com/tis/flink:${project.version}
    hostname: flink
    mem_limit: 2048m
    cpus: '1.0'
    ports:
      - "8081:8081"
    command: ["/bin/bash","-c","./bin/start-cluster.sh && tail -f ./log/flink--standalonesession-0-*.log"]
    environment:
      - TZ=Asia/Shanghai
    depends_on:
      - tis-console
  tis-console:
    image: registry.cn-hangzhou.aliyuncs.com/tis/tis-console:${project.version}
    hostname: tis-console
    mem_limit: "1.5G"
    cpus: '2.5'
    environment:
      - TZ=Asia/Shanghai
      - JAVA_JVM_OPTS=-Xms512m -Xmx1G -XX:MetaspaceSize=100m -XX:MaxMetaspaceSize=300m
    ports:
      - "8080:8080"
      - "56432:56432"
    volumes:
      - ${PWD}/config/config.properties:/opt/app/tis-uber/web-start/conf/tis-web-config/config.properties
      - ${PWD}/data:/opt/data
